### PR TITLE
major update and paradigm shift, making it easier for new users

### PR DESCRIPTION
**Pull request by klaernie**
One of the most recent Grafana updates caused the iframes to be always with scrollbars, so I fixed the problem for myself, then thought I should upstream this.

While preparing a pull request that is not just my internal commit I noticed that there are a few ways this could be improved.
Sorry for the amalgamation of changes, and not preparing individual pull requests for each part.

The one thing I would like to call attention to is the very last commit. After paring everything down and understanding it, it doesn't make sense to me nowadays, to keep this approach, where the user has to take the URL of the dashboard apart, just so that the module can rebuilt another URL.

With the current versions of Grafana there is a Share dialog, that allows you to generate the embed URL directly, guiding the user towards this makes it really easy for newcomers. I prepared a really quick gif that shows the process additionally to the text version itself.

But with this paradigm shift comes also another problem: backwards compatibility. If you care about the current users that upgrade without taking a look at what changed, you should know that they will be surprised by the error message that tells them that no URL was configured.

I was thinking if backward-compatible mode would be advised, but my intuition tells me that this would only cause people not to change anything, as they won't even notice that they are running the legacy path.

If you like to have backwards compatibility anyway, just let me know and I'll implement this.

### CODE REVIEW

**Comment by SvenSommer** [comment]
Hey klaernie,
thanks for the pull request for fixing the scrolling issue and the refactoring. I really like the idea of using the generated Url by Grafana.

Nevertheless, we should not force the current users to update. We should show a notification for now that the current binding of the URL is deprecated and give detailed information (link to the readme.md) on how to change/improve. The "old" way should still be a valid method, so no error messages should be generated.

What do you think?

**Comment by iskrenpp** [comment]
@SvenSommer  I agree here - backwards compatibility is important regardless if module is a young one or long standing.
I may try to help add this support in the next days because I was thinking the same thing as @klaernie  - just passing grafana Url directly is easier than reconstructing it with bits and pieces.

**Comment by iskrenpp** [comment]
@SvenSommer  @klaernie  I have a ready and fully tested code to push to this PR to add support for both old and new config as proposed here. It appears though that I don't have access to push.
Let me know how I can provide this code so that we can all review and merge for the benefit of everyone.

**Comment by klaernie** [comment]
@iskrenpp just open a new PR, if you built on top of my commits it might even automatically close this PR as merged when your PR gets merged. Else I'll happily close this PR for one that is suitable ;)

I thought hard about backwards compatibility back when I opened this PR, but didn't have the time to build a minimal version to accept the old format, then subsequently forgot about it. So I'm really happy to see a better version making it out there.

**Comment by iskrenpp** [comment]
@klaernie  thanks  - I have created PR#18 with yours and my tweaks.

@SvenSommer   - please review and merge if agree. All is tested to work with original config as default and also with new config version.

**Comment by klaernie** [comment]
I read through #18, but didn't feel like it cleaned the code up as far as I'd liked. Since I got some time for it today, I rebased my branch and added the backward compatibility.

The documentation is adjusted to only show the new way of configuring (by providing a `url` property), but the old way continues to work as long as the url is not set explicitly.

**Comment by SvenSommer** [comment]
Pull request was merged into master. Thanks guys!

**Comment by klaernie** [comment]
Actually you merged #18, not #10. Any particular reason for going with #18?

**Comment by SvenSommer** [comment]
Hey klaernie,
my understanding is #18 included your changes and additional ones. If you don't like that your changes were committed on the other branch (and your credit it lost) I will revert the the merge. Sorry, my understanding was you were fine with this.

**Comment by klaernie** [comment]
@SvenSommer I was fine with that, but changed my mind when I took a look at #18. It only contained part of my changes, and didn't retain any of my commits. Since I had an hour I did what you asked me in back in 2021, and built backwards-compatibility into my original branch here in #10.

**Pull request merged**
